version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit    
  save_var:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          echo 'hello world' > ~/oldname
      - run: yum install -y tar gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - oldname
  load_var:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - attach_workspace:
          at: ~/
      - run: |
          OldPipelineID="${cat ~/oldname)"
      - run: |
          echo ${OldPipelineID}
workflows:
  workflow:
    jobs:
      - save_var
      - load_var:
          requires:
            - save_var