version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo 'hello world' > output.txt
      - persis_to_workspace:
          root: /tmp/workspace
          paths: 
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -a
workflows:
  save_and_print_hello_world:
    jobs:
      - save_and_print_hello_world
      - print_output_file:
          requires:
            - save_and_print_hello_world